apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: gopackage
    description: The go package to test
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        generateName: golang-test-
      spec:
        taskRef:
          name: golang-test
        inputs:
          resources:
          - name: source
            resourceSpec:
              type: git
              params:
              - name: url
                value: $(params.gitrepositoryurl)
              - name: revision
                value: $(params.gitrevision)
          params:
          - name: package
            value: $(params.gopackage)
