apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: buildpack-interceptor
spec:
  triggers:
    - name: push-trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-webhook
              secretKey: secret

      bindings:
        - name: git-push-binding
      template:
        name: buildpack-template
