apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-push-binding
spec:
  params:
  - name: gitrevision
    value: $(body.ref)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
