apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kythe-go-
spec:
  serviceAccountName: osscs
  pipelineRef:
    name: kythe-go
  params:
    - name: repo
      value: github.com/tektoncd/pipeline
  workspaces:
  - name: gcs
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
        resources:
          requests:
            storage: 1Gi
