apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: workload-identity
spec:
  workspaces:
  - name: repo
  tasks:
  - name: auth-list
    taskRef:
      name: gcloud
    params:
    - name: ARGS
      value:
      - auth
      - list
  - name: git
    taskRef:
      name: git-clone
    params:
    - name: url
      value: "https://github.com/GoogleCloudPlatform/cloud-run-hello"
    - name: deleteExisting
      value: "true"
    workspaces:
    - name: output
      workspace: repo
  - name: build
    runAfter:
    - git
      #- gcr-init
    taskSpec: 
      steps:
      - name: gcloud-auth
        image: google/cloud-sdk:slim
        command: ["/usr/bin/gcloud"]
        args: ["auth", "configure-docker"]
      - name: ls
        image: ubuntu
        script: |
          find /
      - name: build
        #image: gcr.io/wlynch-test/kaniko/executor:latest
        image: gcr.io/wlynch-test/test-c764cc26288059fef2e5784ac3abb31b
        # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
        env:
          - name: "DOCKER_CONFIG"
            value: "/tekton/home/.docker"
        command:
          - "test"
        args:
          - --context=dir://$(workspaces.input.path)/src
            #- --destination=gcr.io/wlynch-test/kaniko-test
          - --no-push
          - --verbosity=debug
      workspaces:
      - name: input
        mountPath: /src
    workspaces:
    - name: input
      workspace: repo
