apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: workload-identity
spec:
  workspaces:
  - name: repo
  tasks:
#  - name: auth-list
#    taskRef:
#      name: gcloud
#    params:
#    - name: ARGS
#      value:
#      - auth
#      - list
#  - name: gcr-init  
#    taskRef:
#      name: gcloud
#    params:
#    - name: ARGS
#      value:
#      - auth
#      - configure-docker
  - name: git
    taskRef:
      name: git-clone
    params:
    - name: url
      value: "https://github.com/GoogleCloudPlatform/cloud-run-hello"
    - name: deleteExisting
      value: "true"
    workspaces:
    - name: output
      workspace: repo
  - name: build
    runAfter:
    - git
      #- gcr-init
    taskSpec: 
      steps:
      - name: ls
        image: ubuntu
        script: |
          find /
      - name: build
        image: gcr.io/kaniko-project/executor:latest
        # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
        env:
          - name: "DOCKER_CONFIG"
            value: "/tekton/home/.docker/"
        command:
          - /kaniko/executor
        args:
          - --context=dir://$(workspaces.input.path)/src
          - --destination=gcr.io/wlynch-test/kaniko-test
          - --verbosity=debug
      workspaces:
      - name: input
        mountPath: /src
    workspaces:
    - name: input
      workspace: repo
