apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: workload-identity-
spec:
  serviceAccountName: build-robot
  pipelineRef:
    name: workload-identity
  workspaces:
  - name: repo
    persistentVolumeClaim:
      claimName: source-pvc
