apiVersion: bundle.tekton.dev/v1alpha1
kind: GitHub
metadata:
  name: presubmit
spec:
  url: "https://github.com/GoogleCloudPlatform/cloud-run-hello"
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --context=dir://$(workspaces.input.path)/src
        - --destination=gcr.io/wlynch-test/kaniko-test
        - --verbosity=debug