apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: githubapp-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: gha-trig
      interceptors:
        - cel:
            filter: "true" # Bug. We're going to fix this.
            overlays:
            - key: decoded
              expression: "base64(body.message.data)"
      bindings:
      - name: gcr-binding
      template:
        name: git-template
